# Generated by Django 4.1.4 on 2024-07-12 23:43

from django.db import migrations

def create_data(apps, schema_editor):
    User = apps.get_model('api', 'User')
    User(name="Roulettech", email="Roulettech@gmail.com", document="password@123", phone="password@123").save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data)
    ]
